name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Authenticate runner with Registry
      uses: docker/login-action@v2
      with:
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.REGISTRY_REPOSITORY }}/${{ vars.PROJECT }} :$GITHUB_SHA
